//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 03:36:09 PM CEST 
//


package de.fraunhofer.fokus.mdc.util.jaxbmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.fokus.fraunhofer.de}timestamp"/>
 *         &lt;element ref="{http://www.fokus.fraunhofer.de}text"/>
 *         &lt;element ref="{http://www.fokus.fraunhofer.de}integer"/>
 *         &lt;element ref="{http://www.fokus.fraunhofer.de}float"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timestampOrTextOrInteger"
})
@XmlRootElement(name = "data")
public class Data {

    @XmlElements({
        @XmlElement(name = "timestamp", type = Timestamp.class),
        @XmlElement(name = "text", type = Text.class),
        @XmlElement(name = "integer", type = Integer.class),
        @XmlElement(name = "float", type = Float.class)
    })
    protected List<Object> timestampOrTextOrInteger;

    /**
     * Gets the value of the timestampOrTextOrInteger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timestampOrTextOrInteger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimestampOrTextOrInteger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Timestamp }
     * {@link Text }
     * {@link Integer }
     * {@link Float }
     * 
     * 
     */
    public List<Object> getTimestampOrTextOrInteger() {
        if (timestampOrTextOrInteger == null) {
            timestampOrTextOrInteger = new ArrayList<Object>();
        }
        return this.timestampOrTextOrInteger;
    }

}
