#!/bin/bash -x
#$1= gemo.uri
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/storage/target/storage.war -F appName=storage -F "gemoMetadata=@storage.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/userprofile/target/userprofile.war -F appName=userprofile -F "gemoMetadata=@userprofile.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/verfuegbarkeitLadestation/target/verfuegbarkeitLadestation.war -F appName=verfuegbarkeitLadestation -F "gemoMetadata=@verfuegbarkeitLadestation.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/verfuegbarkeitEfz/target/verfuegbarkeitEfz.war -F appName=verfuegbarkeitEfz -F "gemoMetadata=@verfuegbarkeitEfz.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/reservierungLadestationen/target/reservierungLadestation.war -F appName=reservierungLadestation -F "gemoMetadata=@reservierungLadestation.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/openid/target/openid.war -F appName=openid -F "gemoMetadata=@openid.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/cruisingrange/target/cruisingrange.war -F appName=cruisingrange -F "gemoMetadata=@cruisingrange.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/positionLadestation/target/positionLadestation.war -F appName=positionLadestation -F "gemoMetadata=@positionLadestation.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/allgemeineLadestationenDaten/target/allgemeineLadestationenDaten.war -F appName=allgemeineLadestationenDaten -F "gemoMetadata=@allgemeineLadestationenDaten.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/allgemeineEfzDaten/target/allgemeineEfzDaten.war -F appName=allgemeineEfzDaten -F "gemoMetadata=@allgemeineEfzDaten.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/positionEfz/target/positionEfz.war -F appName=positionEfz -F "gemoMetadata=@positionEfz.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/partizipation/target/participation.war -F appName=partizipation -F "gemoMetadata=@partizipation.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/reservierungEfz/target/reservierungEfz.war -F appName=reservierungEfz -F "gemoMetadata=@reservierungEfz.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/payment/target/payments.war -F appName=payments -F "gemoMetadata=@payments.json;type=application/json" $1/odrClientProxy/applications
curl -H "accessToken:token" -H "scope:scope" -H "username:gemodeveloper" -i -F file=@../../src/mobility-services/opnv/target/opnv.war -F appName=opnv -F "gemoMetadata=@opnv.json;type=application/json" $1/odrClientProxy/applications
