//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.28 at 05:03:36 PM MEZ 
//

package de.fhg.fokus.mdc.partizipation.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Complaint complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Complaint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Status"/>
 *         &lt;element name="category" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Category"/>
 *         &lt;element name="creationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="tags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="geolocation" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Geolocation"/>
 *         &lt;element name="address" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Address" minOccurs="0"/>
 *         &lt;element name="averageRating" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}AverageRating" minOccurs="0"/>
 *         &lt;element name="comments" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="comment" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Comment" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ratings" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rating" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Rating" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="photos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="photo" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Photo" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Complaint", propOrder = { "id", "userId", "title",
		"description", "status", "category", "creationTime", "tags",
		"geolocation", "address", "averageRating", "comments", "ratings",
		"photos" })
public class Complaint {

	@XmlElement(required = true)
	protected String id;
	@XmlElement(required = true)
	protected String userId;
	@XmlElement(required = true)
	protected String title;
	@XmlElement(required = true)
	protected String description;
	@XmlElement(required = true)
	protected Status status;
	@XmlElement(required = true)
	protected Category category;
	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar creationTime;
	protected String tags;
	@XmlElement(required = true)
	protected Geolocation geolocation;
	protected Address address;
	protected Float averageRating;
	protected Complaint.Comments comments;
	protected Complaint.Ratings ratings;
	protected Complaint.Photos photos;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the userId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * Sets the value of the userId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUserId(String value) {
		this.userId = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link Status }
	 * 
	 */
	public Status getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link Status }
	 * 
	 */
	public void setStatus(Status value) {
		this.status = value;
	}

	/**
	 * Gets the value of the category property.
	 * 
	 * @return possible object is {@link Category }
	 * 
	 */
	public Category getCategory() {
		return category;
	}

	/**
	 * Sets the value of the category property.
	 * 
	 * @param value
	 *            allowed object is {@link Category }
	 * 
	 */
	public void setCategory(Category value) {
		this.category = value;
	}

	/**
	 * Gets the value of the creationTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getCreationTime() {
		return creationTime;
	}

	/**
	 * Sets the value of the creationTime property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCreationTime(XMLGregorianCalendar value) {
		this.creationTime = value;
	}

	/**
	 * Gets the value of the tags property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * Sets the value of the tags property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTags(String value) {
		this.tags = value;
	}

	/**
	 * Gets the value of the geolocation property.
	 * 
	 * @return possible object is {@link Geolocation }
	 * 
	 */
	public Geolocation getGeolocation() {
		return geolocation;
	}

	/**
	 * Sets the value of the geolocation property.
	 * 
	 * @param value
	 *            allowed object is {@link Geolocation }
	 * 
	 */
	public void setGeolocation(Geolocation value) {
		this.geolocation = value;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link Address }
	 * 
	 */
	public Address getAddress() {
		return address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value
	 *            allowed object is {@link Address }
	 * 
	 */
	public void setAddress(Address value) {
		this.address = value;
	}

	/**
	 * Gets the value of the averageRating property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getAverageRating() {
		return averageRating;
	}

	/**
	 * Sets the value of the averageRating property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setAverageRating(Float value) {
		this.averageRating = value;
	}

	/**
	 * Gets the value of the comments property.
	 * 
	 * @return possible object is {@link Complaint.Comments }
	 * 
	 */
	public Complaint.Comments getComments() {
		return comments;
	}

	/**
	 * Sets the value of the comments property.
	 * 
	 * @param value
	 *            allowed object is {@link Complaint.Comments }
	 * 
	 */
	public void setComments(Complaint.Comments value) {
		this.comments = value;
	}

	/**
	 * Gets the value of the ratings property.
	 * 
	 * @return possible object is {@link Complaint.Ratings }
	 * 
	 */
	public Complaint.Ratings getRatings() {
		return ratings;
	}

	/**
	 * Sets the value of the ratings property.
	 * 
	 * @param value
	 *            allowed object is {@link Complaint.Ratings }
	 * 
	 */
	public void setRatings(Complaint.Ratings value) {
		this.ratings = value;
	}

	/**
	 * Gets the value of the photos property.
	 * 
	 * @return possible object is {@link Complaint.Photos }
	 * 
	 */
	public Complaint.Photos getPhotos() {
		return photos;
	}

	/**
	 * Sets the value of the photos property.
	 * 
	 * @param value
	 *            allowed object is {@link Complaint.Photos }
	 * 
	 */
	public void setPhotos(Complaint.Photos value) {
		this.photos = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="comment" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Comment" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "comment" })
	public static class Comments {

		@XmlElement(required = true)
		protected List<Comment> comment;

		/**
		 * Gets the value of the comment property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the comment property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getComment().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Comment }
		 * 
		 * 
		 */
		public List<Comment> getComment() {
			if (comment == null) {
				comment = new ArrayList<Comment>();
			}
			return this.comment;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="photo" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Photo" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "photo" })
	public static class Photos {

		@XmlElement(required = true)
		protected List<Photo> photo;

		/**
		 * Gets the value of the photo property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the photo property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPhoto().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Photo }
		 * 
		 * 
		 */
		public List<Photo> getPhoto() {
			if (photo == null) {
				photo = new ArrayList<Photo>();
			}
			return this.photo;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="rating" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Rating" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "rating" })
	public static class Ratings {

		@XmlElement(required = true)
		protected List<Rating> rating;

		/**
		 * Gets the value of the rating property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the rating property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getRating().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Rating }
		 * 
		 * 
		 */
		public List<Rating> getRating() {
			if (rating == null) {
				rating = new ArrayList<Rating>();
			}
			return this.rating;
		}

	}

}
