//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.28 at 05:03:36 PM MEZ 
//

package de.fhg.fokus.mdc.partizipation.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ComplaintRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ComplaintRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="geolocation" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Geolocation"/>
 *         &lt;element name="address" type="{http://www.fokus.fraunhofer.de/cm/schema/v1}Address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplaintRequest", propOrder = { "title", "description",
		"tags", "statusId", "categoryId", "geolocation", "address" })
public class ComplaintRequest {

	@XmlElement(required = true)
	protected String title;
	@XmlElement(required = true)
	protected String description;
	protected String tags;
	protected String statusId;
	@XmlElement(required = true)
	protected String categoryId;
	@XmlElement(required = true)
	protected Geolocation geolocation;
	protected Address address;

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the tags property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * Sets the value of the tags property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTags(String value) {
		this.tags = value;
	}

	/**
	 * Gets the value of the statusId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatusId() {
		return statusId;
	}

	/**
	 * Sets the value of the statusId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatusId(String value) {
		this.statusId = value;
	}

	/**
	 * Gets the value of the categoryId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoryId() {
		return categoryId;
	}

	/**
	 * Sets the value of the categoryId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoryId(String value) {
		this.categoryId = value;
	}

	/**
	 * Gets the value of the geolocation property.
	 * 
	 * @return possible object is {@link Geolocation }
	 * 
	 */
	public Geolocation getGeolocation() {
		return geolocation;
	}

	/**
	 * Sets the value of the geolocation property.
	 * 
	 * @param value
	 *            allowed object is {@link Geolocation }
	 * 
	 */
	public void setGeolocation(Geolocation value) {
		this.geolocation = value;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link Address }
	 * 
	 */
	public Address getAddress() {
		return address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value
	 *            allowed object is {@link Address }
	 * 
	 */
	public void setAddress(Address value) {
		this.address = value;
	}

}
